name: IGGG Journal Lollipop
description: Library of IGGG Journal Lollipop
markdown: kramdown
highlighter: :pygments
permalink: /:year/:month/:title/
url: https://iggg.github.io/lollipop/
author:
  name: IGGG
  twitter: IGGGorg
  github: IGGG
  web: www.iggg.org

exclude:
  - README.md
  - lollipop-vol*

timezone: Asia/Tokyo
